zookeeper.connect: "${vcap.services.zookeeper.credentials.zk.cluster}/kafka"
consumer.group: ScoringGroup
gatewayUrl: ${vcap.services.space-shuttle-gateway.credentials.url}

services:
  store:
    baseUrl: http://${vcap.services.space-shuttle-db.credentials.hostname:localhost}
    apiPort: ${vcap.services.space-shuttle-db.credentials.ports.8086/tcp:8086}
    username: ${vcap.services.space-shuttle-db.credentials.username:root}
    password: ${vcap.services.space-shuttle-db.credentials.password:root}
    defaultGroupingInterval: 1m
    defaultTimeLimit: 1h
    databaseName: space-shuttle-demo

  atkscoreengine:
    baseUrl: ${vcap.services.space-shuttle-scoring-engine.credentials.url:http://localhost}

logging:
  level:
    org.trustedanalytics: DEBUG
